<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { getApiError } from '@/api/http'
import ConfirmModal from '@/components/ConfirmModal.vue'
const router=useRouter();const auth=useAuthStore();const form=reactive({name:localStorage.getItem('remembered_name')||sessionStorage.getItem('remembered_name')||'',password:''});const remember=ref(Boolean(localStorage.getItem('remembered_name')));const show=ref(false);const loading=ref(false);const error=ref('');const forgot=ref(false)
async function submit(){error.value='';if(!form.name||!form.password){error.value='请填写姓名和密码';return}loading.value=true;try{await auth.login(form);const storage=remember.value?localStorage:sessionStorage;storage.setItem('remembered_name',form.name);if(!remember.value)localStorage.removeItem('remembered_name');router.push('/home')}catch(e){error.value=getApiError(e,'登录失败')}finally{loading.value=false}}
</script>
<template><section class="login-shell"><div class="brand-side"><svg class="logo" viewBox="0 0 100 100" aria-label="挂图作战系统 Logo"><defs><linearGradient id="lg" x1="0" x2="1"><stop stop-color="#42d9ff"/><stop offset="1" stop-color="#547dff"/></linearGradient></defs><path d="M18 72 38 50l17 12 27-34" fill="none" stroke="url(#lg)" stroke-width="7" stroke-linecap="round"/><circle cx="18" cy="72" r="7" fill="#42d9ff"/><circle cx="38" cy="50" r="7" fill="#42d9ff"/><circle cx="55" cy="62" r="7" fill="#42d9ff"/><circle cx="82" cy="28" r="7" fill="#547dff"/><path d="M18 86h64M28 18v68M52 18v68M76 18v68" opacity=".2" stroke="#62d8ff"/></svg><p class="brand-kicker">DIGITAL COMMAND CENTER</p><h1>挂图作战系统</h1><h2>让任务清晰可见，让协同高效推进</h2><p class="intro">围绕重点任务、年度任务与月度任务，实现任务创建、分解、分发、执行、反馈与闭环管理，让每一项工作有目标、有责任、有进度、有结果。</p><div class="feature-tags"><span>任务全流程管理</span><span>多角色协同推进</span><span>进度透明可追溯</span></div></div><div class="login-card panel"><p class="eyebrow">身份验证</p><h2>欢迎登录</h2><p class="muted">请输入您的账号信息进入系统</p><form class="form-grid" @submit.prevent="submit"><label>姓名<input v-model.trim="form.name" autocomplete="username" placeholder="请输入姓名" /></label><label>密码<div class="password-wrap"><input v-model="form.password" :type="show?'text':'password'" autocomplete="current-password" placeholder="请输入密码" /><button type="button" class="eye" :aria-label="show?'隐藏密码':'显示密码'" @click="show=!show">{{show?'◉':'◎'}}</button></div></label><div class="login-options"><label class="check"><input v-model="remember" type="checkbox" />记住我</label><button type="button" class="link-button" @click="forgot=true">忘记密码？</button></div><p v-if="error" class="error">{{error}}</p><button class="submit" :disabled="loading">{{loading?'登录中…':'登录系统'}}</button></form><p class="register-entry">还没有密码？<RouterLink to="/register">立即注册</RouterLink></p></div><ConfirmModal :open="forgot" title="忘记密码" message="当前系统暂未配置自助找回密码功能。如需重置密码，请联系系统管理员处理。" confirm-text="我知道了" @confirm="forgot=false" @cancel="forgot=false" /></section></template>
<style scoped>.login-shell{width:min(1120px,100%);display:grid;grid-template-columns:minmax(0,1.05fr) minmax(420px,500px);align-items:center;gap:72px;padding:42px}.brand-side{padding:20px 0}.logo{width:104px;height:104px;animation:breathe 4s ease-in-out infinite}.brand-kicker{color:#56cfff;letter-spacing:.2em;font-size:11px;margin:20px 0 10px}.brand-side h1{font-size:clamp(40px,5vw,68px);margin:0;background:linear-gradient(100deg,#effbff,#66cfff 55%,#8395ff);color:transparent;background-clip:text}.brand-side h2{font-size:22px;font-weight:500;color:#b9e2f5;margin:18px 0}.intro{max-width:560px;color:#91acc1;line-height:2;font-size:15px}.feature-tags{display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.feature-tags span{padding:9px 13px;border:1px solid #286083;border-radius:99px;color:#83d8f7;background:#0d2b42aa}.login-card{width:100%;padding:42px}.login-card h2{font-size:32px;margin:8px 0}.password-wrap{position:relative}.password-wrap input{padding-right:48px}.eye{position:absolute;right:5px;top:4px;width:38px;height:38px;padding:0;border:0;background:transparent;color:#69c8ee;font-size:20px}.login-options{display:flex;justify-content:space-between;align-items:center}.check{display:flex;display:flex;align-items:center;gap:8px}.check input{width:auto}.link-button{border:0;background:transparent;padding:0;color:#67c9f2}.submit{width:100%;font-size:15px;padding:13px}.register-entry{text-align:center;color:#8da6bc;margin:24px 0 0}.register-entry a{color:#64cdf7;margin-left:5px}.form-grid{max-width:none}.error{margin:0}.muted{margin-top:-4px;color:#8da6bc}@keyframes breathe{50%{filter:drop-shadow(0 0 16px #36cfff88);transform:translateY(-3px)}}@media(max-width:800px){.login-shell{grid-template-columns:1fr;gap:10px;padding:20px}.brand-side{text-align:center;padding:5px}.brand-side h1{font-size:42px}.intro{margin:auto}.feature-tags{justify-content:center}.login-card{width:min(500px,100%);justify-self:center;padding:30px 24px}}@media(prefers-reduced-motion:reduce){.logo,.panel{animation:none}}
</style>
