<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { departments, register } from '@/api/auth'; import { getApiError } from '@/api/http'
const positions=[['general_manager','总经理'],['deputy_general_manager','副总经理'],['section_chief','科长'],['deputy_section_chief','副科长'],['team_leader','组长'],['member','组员']];const form=reactive({name:'',password:'',confirm_password:'',position:'member',department_id:'',job_title:'',responsibility:''});const list=ref([]),error=ref(''),success=ref(''),loading=ref(false),router=useRouter()
onMounted(async()=>{try{list.value=(await departments()).data}catch(e){error.value=getApiError(e,'部门加载失败')}})
async function submit(){error.value='';success.value='';if(!form.name||!form.password||!form.confirm_password||!form.department_id){error.value='请填写完整注册信息';return}if(form.password!==form.confirm_password){error.value='两次输入的密码不一致';return}loading.value=true;try{await register(form);success.value='注册申请已提交，请等待管理员审核';setTimeout(()=>router.replace('/login'),1500)}catch(e){error.value=getApiError(e)}finally{loading.value=false}}
</script>
<template><section class="register-shell"><div class="register-brand"><div class="brand-symbol">◈</div><p class="brand-kicker">数字化指挥中心</p><h1>挂图作战系统</h1><h2>让任务清晰可见，让协同高效推进</h2><p>围绕重点任务、年度任务与月度任务，实现任务创建、分解、分发、执行、反馈与闭环管理，让每一项工作有目标、有责任、有进度、有结果。</p><div class="tags"><span>任务全流程管理</span><span>多角色协同推进</span><span>进度透明可追溯</span></div></div><section class="panel register-card"><p class="eyebrow">注册申请</p><h2>加入系统</h2><form class="register-form" @submit.prevent="submit"><label>姓名<input v-model.trim="form.name" required /></label><div class="two-col"><label>密码<input v-model="form.password" type="password" minlength="6" required /></label><label>确认密码<input v-model="form.confirm_password" type="password" required /></label></div><div class="two-col"><label>职位<select v-model="form.position"><option v-for="p in positions" :key="p[0]" :value="p[0]">{{p[1]}}</option></select></label><label>部门<select v-model="form.department_id" required><option value="" disabled>请选择部门</option><option v-for="d in list" :key="d.id" :value="d.id">{{d.name}}</option></select></label></div><label>用户岗位<input v-model="form.job_title" placeholder="可填写无" /></label><label>职责描述<textarea v-model="form.responsibility" rows="4" /></label><p v-if="error" class="error">{{error}}</p><p v-if="success" class="success">{{success}}</p><button class="submit" :disabled="loading">{{loading?'提交中…':'提交注册申请'}}</button></form><p class="back-login">已有账号？<RouterLink to="/login">返回登录</RouterLink></p></section></section></template>
<style scoped>.register-shell{width:min(1220px,100%);display:grid;grid-template-columns:minmax(0,1fr) minmax(520px,620px);gap:70px;align-items:center;padding:28px}.register-brand{padding:20px}.brand-symbol{color:#51d4ff;font-size:64px}.brand-kicker{color:#5bd2ff;letter-spacing:.18em}.register-brand h1{font-size:clamp(42px,5vw,68px);margin:14px 0;background:linear-gradient(100deg,#fff,#62d8ff,#8892ff);color:transparent;background-clip:text}.register-brand h2{color:#c0e5f5;font-weight:500}.register-brand>p:not(.brand-kicker){color:#91acc1;line-height:2;max-width:550px}.tags{display:flex;gap:10px;flex-wrap:wrap;margin-top:25px}.tags span{padding:9px 13px;border:1px solid #286083;border-radius:99px;color:#83d8f7;background:#0d2b42aa}.register-card{width:100%;max-height:calc(100vh - 56px);overflow:auto;padding:38px}.register-card h2{font-size:30px;margin:8px 0 20px}.register-form{display:grid;gap:15px}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:15px}.submit{width:100%}.back-login{text-align:center;color:#8da6bc}.back-login a{color:#63cdf6;margin-left:5px}@media(max-width:850px){.register-shell{grid-template-columns:1fr;gap:10px;padding:14px}.register-brand{text-align:center;padding:5px}.register-brand h1{font-size:42px}.register-brand>p:not(.brand-kicker){margin:auto}.tags{justify-content:center}.register-card{max-height:none;padding:26px 20px}}@media(max-width:500px){.two-col{grid-template-columns:1fr}}
</style>
