<script setup>
import { onMounted, reactive, ref } from 'vue'
import { actionUser, deleteUser, listUsers } from '@/api/admin'
import { getApiError } from '@/api/http'
import { getPositionLabel, getAccountStatusLabel, getRegisterStatusLabel } from '@/utils/labels'
import ConfirmModal from '@/components/ConfirmModal.vue'
const users=ref([]), loading=ref(false), error=ref(''), total=ref(0); const filters=reactive({name:'',department_id:'',position:'',account_status:'',register_status:''}); const modal=ref({open:false,title:'',message:'',confirmText:'',run:null})
async function load(){loading.value=true;try{const r=await listUsers(filters);users.value=r.data.results||[];total.value=r.data.count||0}catch(e){error.value=getApiError(e,'用户列表加载失败')}finally{loading.value=false}}
function ask(u,a){const m={enable:['确认启用账号',`确定要启用用户“${u.name}”吗？`,'确定启用'],disable:['确认禁用账号',`确定要禁用用户“${u.name}”吗？禁用后该用户将无法登录。`,'确定禁用'],'grant-admin':['确认授予系统管理员权限',`确定要授予用户“${u.name}”系统管理员权限吗？`,'确定授予'],'revoke-admin':['确认取消系统管理员权限',`确定要取消用户“${u.name}”的系统管理员权限吗？`,'确定取消']};const x=m[a];modal.value={open:true,title:x[0],message:x[1],confirmText:x[2],run:()=>actionUser(u.id,a)}}
function remove(u){modal.value={open:true,title:'确认删除用户',message:`确定要逻辑删除用户“${u.name}”吗？删除后用户将不再显示在正常用户列表中。`,confirmText:'确定删除',run:()=>deleteUser(u.id)}}
async function confirmModal(){const fn=modal.value.run;modal.value.open=false;try{await fn();await load()}catch(e){error.value=getApiError(e,'操作失败')}}
onMounted(load)
</script>
<template><section class="panel"><h1>系统管理中心</h1><div class="actions"><input v-model="filters.name" placeholder="按姓名查询"><select v-model="filters.account_status"><option value="">全部账号状态</option><option value="enabled">正常</option><option value="disabled">已禁用</option></select><select v-model="filters.register_status"><option value="">全部审核状态</option><option value="pending">待审核</option><option value="approved">已通过</option><option value="rejected">已驳回</option></select><button @click="load">查询</button></div><p v-if="loading" class="muted">加载中…</p><p v-if="error" class="error">{{error}}</p><p v-if="!loading&&!users.length" class="muted">暂无数据</p><div v-else class="table-wrap"><table><thead><tr><th>姓名</th><th>职位</th><th>部门</th><th>岗位</th><th>账号状态</th><th>审核状态</th><th>系统管理员</th><th>操作</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.name}}</td><td>{{getPositionLabel(u.position)}}</td><td>{{u.department?.name||'—'}}</td><td>{{u.job_title||'无'}}</td><td>{{getAccountStatusLabel(u.account_status)}}</td><td>{{getRegisterStatusLabel(u.register_status)}}</td><td>{{u.is_system_admin?'是':'否'}}</td><td class="actions"><button @click="ask(u,u.account_status==='disabled'?'enable':'disable')">{{u.account_status==='disabled'?'启用账号':'禁用账号'}}</button><button v-if="!u.is_system_admin" @click="ask(u,'grant-admin')">授予管理员</button><button v-else @click="ask(u,'revoke-admin')">取消管理员</button><button class="danger" @click="remove(u)">逻辑删除</button></td></tr></tbody></table></div><p class="muted">共 {{total}} 条</p><ConfirmModal :open="modal.open" :title="modal.title" :message="modal.message" :confirm-text="modal.confirmText" @confirm="confirmModal" @cancel="modal.open=false" /></section></template>
