<script setup>
import { onMounted, reactive, ref } from 'vue'
import { actionUser, deleteUser, downloadTemplate, importUsers, listUsers } from '@/api/admin'
import { departments } from '@/api/auth'
import { getApiError } from '@/api/http'
const users=ref([]); const deps=ref([]); const loading=ref(false); const error=ref(''); const filters=reactive({name:'',department_id:'',position:'',account_status:'',register_status:''}); const file=ref(null); const total=ref(0)
async function load(){loading.value=true;error.value='';try{const r=await listUsers(filters);users.value=r.data.results||[];total.value=r.data.count||0}catch(e){error.value=getApiError(e,'用户列表加载失败')}finally{loading.value=false}}
onMounted(async()=>{try{deps.value=(await departments()).data}catch(e){error.value=getApiError(e,'部门加载失败')}load()})
async function act(u,a,data={}){if(!confirm(`确认执行${a}操作？`))return;try{await actionUser(u.id,a,data);await load()}catch(e){error.value=getApiError(e,'操作失败')}}
async function remove(u){if(confirm('确认逻辑删除该用户？'))try{await deleteUser(u.id);await load()}catch(e){error.value=getApiError(e,'删除失败')}}
async function template(){try{const r=await downloadTemplate();const a=document.createElement('a');a.href=URL.createObjectURL(r.data);a.download='users_template.xlsx';a.click()}catch(e){error.value=getApiError(e,'模板下载失败')}}
async function upload(){if(!file.value)return;try{const r=await importUsers(file.value);alert(`导入完成：成功 ${r.data.success_count} 行，共 ${r.data.total} 行`);await load()}catch(e){error.value=getApiError(e,'导入失败')}}
</script>
<template><section class="panel"><p class="eyebrow">SYSTEM / USERS</p><h1>系统管理中心</h1><div class="actions"><input v-model="filters.name" placeholder="按姓名查询"><select v-model="filters.department_id"><option value="">全部部门</option><option v-for="d in deps" :key="d.id" :value="d.id">{{d.name}}</option></select><select v-model="filters.account_status"><option value="">账号状态</option><option value="enabled">启用</option><option value="disabled">禁用</option></select><button @click="load">查询</button><button @click="template">下载模板</button><input type="file" accept=".xlsx" @change="file=$event.target.files[0]"><button @click="upload">批量导入</button></div><p v-if="loading" class="muted">加载中…</p><p v-if="error" class="error">{{error}}</p><p v-if="!loading&&!users.length" class="muted">暂无数据</p><div v-else class="table-wrap"><table><thead><tr><th>姓名</th><th>职位</th><th>部门</th><th>岗位</th><th>账号状态</th><th>审核状态</th><th>系统管理员</th><th>操作</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.name}}</td><td>{{u.position}}</td><td>{{u.department?.name||'—'}}</td><td>{{u.job_title||'无'}}</td><td>{{u.account_status}}</td><td>{{u.register_status}}</td><td>{{u.is_system_admin?'是':'否'}}</td><td class="actions"><button v-if="u.account_status==='disabled'" @click="act(u,'enable')">启用</button><button v-else @click="act(u,'disable')">禁用</button><button v-if="!u.is_system_admin" @click="act(u,'grant-admin')">授予管理员</button><button v-else @click="act(u,'revoke-admin')">取消管理员</button><button class="danger" @click="remove(u)">删除</button></td></tr></tbody></table></div><p class="muted">共 {{total}} 条</p></section></template>
